// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVZBHqUlFIQkdS-G_g-aTq8Sf71GPZZrk',
    appId: '1:619666010560:web:153d7d5838fa3023191825',
    messagingSenderId: '619666010560',
    projectId: 'proyecto-grado-b9dad',
    authDomain: 'proyecto-grado-b9dad.firebaseapp.com',
    storageBucket: 'proyecto-grado-b9dad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfs1YqQo9nkV2zol9HOVUHSiRYIgKZNz4',
    appId: '1:619666010560:android:e0135ee4cff11527191825',
    messagingSenderId: '619666010560',
    projectId: 'proyecto-grado-b9dad',
    storageBucket: 'proyecto-grado-b9dad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwa1lcfmiArPf5DojJhW4Yu38ImsKavXI',
    appId: '1:619666010560:ios:0d954b85eb775ab0191825',
    messagingSenderId: '619666010560',
    projectId: 'proyecto-grado-b9dad',
    storageBucket: 'proyecto-grado-b9dad.appspot.com',
    iosBundleId: 'com.example.tutoriasEstudiantes',
  );
}
